title: "Kai-Hua (Kelvin) Wang"
description: "B.S. in Mechanical Engineering @ NTU"
url: https://kelvin1106.github.io
baseurl: ""

author:
  location: "Taipei, Taiwan"
  employer: "National Taiwan University"
  email: "kaihuawang.work@gmail.com"
  github: "Kelvin1106"
  linkedin: "https://www.linkedin.com/in/kaihuawang/"
